import Head from 'next/head'
import svg from '../../../public/favicon.ico'
import { Navbar } from '@ui';
import clsx from 'clsx';

interface Props {
  children: JSX.Element | JSX.Element[];
  loading: boolean;
}

export const RootLayout: React.FC<Props> = ({ children, loading = false }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href={svg.src} />
        <title>Shop</title>
      </Head>


      <main className={clsx(
        "",
        { "overflow-hidden h-screen": loading }
      )}>
        <Navbar />
        <div className='py-8'>
          {children}
        </div>
      </main>
    </>
  )
}
